package com.goldfinance.entity;

public enum NotificationType {
    LOAN_CREATED,
    LOAN_STATUS_CHANGED,
    LOAN_RENEWED,
    LOAN_CLOSED,
    LOAN_OVERDUE,
    LOAN_DEFAULTED,
    PAYMENT_RECEIVED,
    PAYMENT_OVERDUE,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    BANK_LOAN_CREATED,
    BANK_LOAN_RENEWAL_DUE,
    BANK_LOAN_EXPIRED,
    SYSTEM_ALERT
}